Repository cornerstonejs/cornerstoneTools, pull requests merged in 2018-11, with the labels that each got.

#639 Fixes being able to set shadowOptions to falsy values, adds shadowBlu…
  src/util/drawing.js
  src/util/getDefault.js
Labels: vNext, version 2

#715 fix(src/magnify.js): fix magnify use cornerstone.enable bug whith use…
  src/imageTools/magnify.js
Labels: vNext, verified bug, version 2

#698 Feature to disable probe textbox by setting the configuration.
  src/imageTools/probe.js
Labels: enhancement, version 2
