Repository cornerstonejs/cornerstoneTools, pull requests merged in 2019-08, with the labels that each got.

#1008 fix: #998 eslint auto fix and fix moveEndHandler will trigger that when i click the enabled element, but it is not the same with 2.4.x"
  src/manipulators/moveNewHandle.js
  src/tools/annotation/EllipticalRoiTool.test.js
  src/tools/annotation/FreehandMouseTool.js
  src/tools/annotation/ProbeTool.test.js
  src/tools/annotation/RectangleRoiTool.test.js
  src/tools/base/BaseAnnotationTool.js
  src/tools/cursors/MouseCursor.js
Labels: Bug: Fix :bug:

#960 vNext - spherical brush
  index.html
  netlify-example/brush/index.html
  netlify-example/crosshairs/index.html
  netlify-example/metaDataProvider.js
  src/index.js
  src/store/modules/brushModule.js
  src/tools/segmentation/SphericalBrushTool.js
  src/tools/segmentation/index.js
Labels: vNext

#923 feat(stackPrefetch.js): Adds events to report stack prefetching progress
  src/events.js
  src/stackTools/stackPrefetch.js
Labels: PR: Awaiting Review :eyes:
