Repository cornerstonejs/cornerstoneTools, pull requests merged in 2019-02, with the labels that each got.

#765 fix(FreehandMouseTool): use pixelCoordinates to measure spacing instead of canvasCoordinates
  src/tools/annotation/EllipticalRoiTool.js
  src/tools/annotation/FreehandMouseTool.js
  src/tools/annotation/RectangleRoiTool.js
  src/util/debounce.js
  src/util/isObject.js
  src/util/throttle.js
Labels: 🐛 Bug: Fix

#760 fix(CobbAngle): Show angle measurement text box
  src/tools/annotation/CobbAngleTool.js
Labels: Awaiting Review, 🐛 Bug: Fix

#786 Fix freehand tool doesn't fire MEASUREMENT_MODIFIED event #774
  .eslintrc.js
  examples/freehandRoi/index.html
  src/imageTools/freehand.js
Labels: 💻 Change: Implementation, 📦 Version 2, 📦 Version 3

#785 Fix deactivating/canceling freehand while drawing is not working #784
  examples/freehandRoi/index.html
  src/imageTools/freehand.js
Labels: 🐛 Bug: Fix, 📦 Version 2

#783 Fix Freehand handles not closed after loading state data. Issue #775
  examples/toolState/index.html
  src/util/freehand/dragObject.js
Labels: 🐛 Bug: Fix, 📦 Version 2
